create table category (id bigint not null auto_increment, category_name varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, amount decimal(19,2), description longtext, recipe_id bigint, uom_id bigint, primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, notes longtext, recipe_id bigint, primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, cook_time integer, description varchar(255), difficulty varchar(255), directions longtext, image longblob, prep_time integer, servings integer, source varchar(255), url varchar(255), notes_id bigint, primary key (id)) engine=InnoDB;
create table recipe_category (recipe_id bigint not null, category_id bigint not null, primary key (recipe_id, category_id)) engine=InnoDB;
create table unit_of_mesure (id bigint not null auto_increment, uom varchar(255), primary key (id)) engine=InnoDB;
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK7vp3wo128syjx6nri9ru52sle foreign key (uom_id) references unit_of_mesure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);
INSERT INTO category (category_name) VALUES ('American');
INSERT INTO category (category_name) VALUES ('Mexican');
INSERT INTO category (category_name) VALUES ('Italian');
INSERT INTO category (category_name) VALUES ('Chinese');
INSERT INTO unit_of_mesure (uom) VALUES ('Teaspoon');
INSERT INTO unit_of_mesure (uom) VALUES ('Tablespoon');
INSERT INTO unit_of_mesure (uom) VALUES ('Cup');
INSERT INTO unit_of_mesure (uom) VALUES ('Each');
INSERT INTO unit_of_mesure (uom) VALUES ('Pinch');
INSERT INTO unit_of_mesure (uom) VALUES ('Pint');
INSERT INTO unit_of_mesure (uom) VALUES ('Dash');