spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_prod_user
    password: azerty
    platform: mysql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false